CXX = g++
CXXFLAGS = -g -Wall -pedantic -std=c++17

Test: test.o yahtzee.o factory.o ruletypes.o scoresheet.o rule.o
	${CXX} ${CXXFLAGS} -o Test test.o yahtzee.o factory.o ruletypes.o scoresheet.o rule.o

test.o:

yahtzee.o:

factory.o:

ruletypes.o:

scoresheet.o:

rule.o:
